apiurl: https://demo.cachethq.io/api/v1
apitoken: 9yMHsdioQosnyVK4iCVR
insecureapi: true
monitors:
  - name: google
    type: http
    url:  https://google.com
    stricttls: true
    threshold: 80
    componentid: 1
    interval: 10
    timeout: 5
    expectedstatuscode: 200
    headers:
      - name: Authorization
        value: Basic <xyz>